rewriter:
  host:
    - matcher: ^m[a-z]*\.nytimes.com
      replacement: www.nytimes.com
    - matcher: m[a-z]*\.([a-z0-9\-\.]*nytimes.com)
      replacement: \1
  link:
    host: m(?<prefix>[a-z]*)\.[a-z0-9\-\.]*nytimes.com
    matcher: (^|\/\/|\"|\')(?!m$prefix\.)(www\.)?([a-z0-9\-\.]*)nytimes.com
    replacement: \1m$prefix.\3nytimes.com
  cookie_domain:
    matcher: \.?(www\.)?([a-z0-9\-\.]*nytimes.com)
    replacement: .\2

