rewriter:
  host:
    - matcher: ^m[a-z]*\.nytimes\.com
      replacement: www.nytimes.com
    - matcher: ^m[a-z]*\.([a-z0-9\-\.]*nytimes\.com)
      replacement: \1
    - matcher: (.*)nytimes(.*)\.com
      replacement: $1nytimes.com
  link:
    host: (?<prefix>.*)nytimes\.(?<suffix>.*)
    matcher: (^|\/\/|\"|\')(www\.)?([a-z0-9\-\.]*)nytimes\.com
    replacement: $1$prefix$3nytimes.$suffix
  cookie_domain:
    host: (?<prefix>.*)nytimes\.(?<suffix>.*)
    matcher: \.?(www\.)?([a-z0-9\-\.]*)nytimes\.com
    replacement: .$2nytimes.$suffix
    missing_replacement: .nytimes.$suffix

